# Generated by Django 3.1.4 on 2021-01-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210123_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='cate_id',
        ),
    ]
