# Generated by Django 3.1.4 on 2021-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210123_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='cate_id',
            new_name='category',
        ),
    ]
